import{i as p,S as f}from"./assets/vendor-9310f15c.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerpolicy&&(t.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?t.credentials="include":e.crossorigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();const l=document.querySelector(".form"),a=document.querySelector(".gallery");let c;l.addEventListener("submit",g);function g(s){s.preventDefault(),a.innerHTML="",document.querySelector(".loader").classList.remove("hidden");const r=l.elements.q.value;h(r).then(o=>{o.hits.length===0&&p.show({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",backgroundColor:"#EF4040",titleColor:"#FFFFFF",messageColor:"#FFFFFF"}),y(o.hits)}).catch(o=>console.log(o)).finally(()=>{document.querySelector(".loader").classList.add("hidden"),l.reset()})}function h(s){const r="42001706-084c655b89d9d100c07cefb17",o="https://pixabay.com/api/",i=new URLSearchParams({key:r,q:s,image_type:"photo",orientation:"horizontal",safesearch:"true"}),e=`${o}?${i}`;return fetch(e).then(t=>{if(!t.ok)throw new Error(t.status);return t.json()})}function y(s){const r=s.map(o=>{const{webformatURL:i,largeImageURL:e,tags:t,likes:n,views:u,comments:m,downloads:d}=o;return`<li class="gallery-item">
                <a class="gallery-link" href=${e}>
                <img src=${i} alt="${t}" /></a>
                    <ul class="image-desc">
                        <li class="image-desc-item"><p>Likes</p><p>${n}</p></li>
                        <li class="image-desc-item"><p>Views</p><p>${u}</p></li>
                        <li class="image-desc-item"><p>Comments</p><p>${m}</p></li>
                        <li class="image-desc-item"><p>Downloads</p><p>${d}</p></li>
                    </ul>
            </li>`});L(r),c.refresh()}function L(s){a.innerHTML=s.join(""),c=new f(".gallery a",{captionDelay:250,captionsData:"alt"})}
//# sourceMappingURL=commonHelpers.js.map
